# frozen_string_literal: true

source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-contrib'
gem 'faye-websocket'
gem 'puma'
gem 'rackup'

# gem 'oga'
gem 'json'
gem 'mime-types'
gem 'sorbet-runtime'
gem 'nanoid'
gem 'mongo'
gem 'bigdecimal'

group :backends do
  gem 'webrick'
  gem 'thin' 
end

group :performance do
  gem "ruby-prof"
end

group :develop do
  gem "sorbet"
  gem "tapioca"
  gem 'irb'
  #gem 'rdoc'
  ##gem "google-apis-youtube_v3"
  #gem 'test-unit'
  ##gem "faye-websocket"
  #gem 'websocket-client-simple'
  #gem "rake"
  #gem "ffi-rzmq"
  #gem "iruby"
  #gem "nanoid"
end
