# frozen_string_literal: true

source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-contrib'
gem 'websocket-client-simple'
gem 'puma'
gem 'rackup'

# gem 'oga'
gem 'json'
gem 'mime-types'
gem 'sorbet-runtime'
gem 'nanoid'
gem 'mongo'
gem 'bigdecimal'
gem 'multipart-post'

group :server do
  gem "faye-websocket"
end

group :backends do
  gem 'webrick'
  gem 'thin' 
end

group :performance do
  gem "ruby-prof"
end

group :develop do
  gem "sorbet"
  gem "tapioca"
  gem 'irb'
  #gem 'rdoc'
  ##gem "google-apis-youtube_v3"
  #gem 'test-unit'
  #gem "rake"
  #gem "ffi-rzmq"
  #gem "iruby"
  #gem "nanoid"
end

gem "redcarpet", "~> 3.6"
